---
- name: Развертывание контейнера Docker и установка Django
  hosts: web_servers
  become: yes

  tasks:
    - name: Установка Docker на Ubuntu
      command: apt install docker.io -y

    - name: Запуск службы Docker
      service:
        name: docker
        state: started

    - name: Установка библиотеки Docker SDK for Python
      pip:
        name: docker
      tags: docker-deploy

    - name: Скопировать Dockerfile и приложение на сервер
      copy:
        src: ./
        dest: /tmp/docker_project
      become: true

    - name: Собрать Docker контейнер
      command: docker build -t app_ansible_2 /tmp/docker_project
      become: true

    - name: Запустить Docker контейнер
      command: docker run -d -p 8080:8080 --name app_ansible_2 app_ansible_2
      become: true
