---
- name: Install and configure MySQL
  hosts: web_servers
  become: yes

  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL user
      mysql_user:
        login_user: root
        login_password: '1234'
        name: root
        password: '1234'
        host_all: yes
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create MySQL database
      mysql_db:
        login_user: root
        login_password: '1234'
        name: dbname
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
